name: Fly Deploy cd
on: 
  push:
  schedule:
    - cron: '0 8 3 * *'
  workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: ${{ secrets.APP_NAME }}
  SQLUSER: ${{ secrets.SQLUSER }}
  DATABASE: ${{ secrets.DATABASE }}
  SQLPASSWORD: ${{ secrets.SQLPASSWORD }}
  SQLHOST: ${{ secrets.SQLHOST }}
  SQLPORT: ${{ secrets.SQLPORT }}
  SQLNAME: ${{ secrets.SQLNAME }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          sh ./deploy.sh
